name: swipe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_staggered_grid_view: 0.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg:
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/img/house/
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat_Thin.ttf
          weight: 100
          style: normal
        - asset: assets/fonts/Montserrat_ExtraLight.ttf
          weight: 200
          style: normal
        - asset: assets/fonts/Montserrat_Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Montserrat_Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Montserrat_Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Montserrat_Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Montserrat_ExtraBold.ttf
          weight: 800
          style: normal