import 'package:swipe/models/adproduct.dart';
import 'package:swipe/models/favnovostroi.dart';
import 'package:swipe/models/product.dart';

import '../models/favproduct.dart';
import '../models/novostroi.dart';

List<Product> productsList = [
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house1.png',
    avaibleTime: "15:00",
    id: 1,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house2.png',
    avaibleTime: "15:00",
    id: 2,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 6,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: true,
  ),
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 7,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: true,
    accentRed: false,
  ),
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: true,
    accentGreen: false,
    accentRed: false,
  ),
  Product(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: true,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
];

List<Novostroi> novostrois = [
  Novostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  Novostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi2.jpg',
    id: 4,

  ),


];
List<AdProduct> adproducts = [
  AdProduct(
  price: "3 400 000",
  rooms: 5,
  quadratmetr: 28.5,
  etage: "1/8",
  title: 'Product 1',
  description1: 'Центральный',
  description2: 'Темерязева',
  category: 'Category A',
  imageAssetPath: 'assets/img/house/house3.png',
  avaibleTime: "15:00",
  id: 7,
    isFavorite: false,
  )

];
List<FavProduct> favProducts = [
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),
  FavProduct(
    price: "3 400 000",
    rooms: 1,
    quadratmetr: 28.5,
    etage: "1/8",
    title: 'Product 1',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/house3.png',
    avaibleTime: "15:00",
    id: 8,
    isFavorite: false,
    isUrgentSale: false,
    bargainPrice: false,
    accentGreen: false,
    accentRed: false,
  ),

];

List<FavNovostroi> favnovostrois = [
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),
  FavNovostroi(
    price: "3 400 000",
    quadratmetr: 40,
    title: 'ЖК "Миллениум Тауэр"',
    description1: 'Центральный',
    description2: 'Темерязева',
    category: 'Category A',
    imageAssetPath: 'assets/img/house/novostroi1.png',
    id: 3,

  ),


];